spring.application.name=AgendamentoWeb
server.port=8080
#spring.datasource.url=mysql://localhost:3306/first_spring_app
#spring.datasource.username=root
#spring.datasource.password=root

#spring.datasource.url=jdbc:h2:mem:ecommerce_db
spring.datasource.url=jdbc:h2:file:~/ecommerce_db

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=bybocs
spring.datasource.password=sherlock

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


debug=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
api.security.token.secret=${JWT_SECRET:my-secret-key}